# Generated by Django 4.2.6 on 2023-10-26 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chronicle', '0003_alter_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.CharField(max_length=32),
        ),
    ]
