# Generated by Django 4.2.6 on 2023-11-01 11:29

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chronicle', '0005_alter_post_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), size=None), size=None)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2023, 11, 1, 11, 29, 1, 696893, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='user',
            name='family',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.AddField(
            model_name='album',
            name='contributors',
            field=models.ManyToManyField(related_name='album_contributors', to='chronicle.user'),
        ),
        migrations.AddField(
            model_name='album',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album_creator', to='chronicle.user'),
        ),
        migrations.AddField(
            model_name='album',
            name='participants',
            field=models.ManyToManyField(related_name='album_participants', to='chronicle.user'),
        ),
    ]
