# Generated by Django 4.2.6 on 2023-11-02 09:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chronicle', '0007_album_title_alter_user_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='images',
        ),
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(default=datetime.date(2023, 11, 2)),
        ),
    ]
