# Generated by Django 4.2.6 on 2023-11-04 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chronicle', '0010_album_images_folder_id_alter_album_event_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='images_folder_id',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
