# Generated by Django 4.2.6 on 2023-11-04 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chronicle', '0011_alter_album_images_folder_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='title',
            field=models.CharField(default=None, max_length=64),
        ),
    ]
