# Generated by Django 4.2.6 on 2023-11-04 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chronicle', '0012_alter_album_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='title',
            field=models.CharField(default=None, max_length=64, unique=True),
        ),
    ]
